###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Wu Wenxu'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': {'repo': 'ValMystletainn/ob-notes'}}
copyright = '2024'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx.ext.mathjax', 'sphinx_tippy', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_css_files = ['custom.css']
html_favicon = ''
html_logo = 'logo.png'
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': ''}, 'path_to_docs': 'docs', 'repository_url': 'https://github.com/executablebooks/jupyter-book', 'repository_branch': 'master', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': ''}, 'use_repository_button': True, 'use_edit_page_button': False, 'use_issues_button': True, 'pygment_light_style': 'vs', 'use_fullscreen_button': False, 'navbar_start': ['navbar-logo'], 'navbar_center': ['navbar-nav'], 'navbar_end': [], 'article_header_start': ['toggle-primary-sidebar.html'], 'article_header_end': ['toggle-secondary-sidebar.html'], 'secondary_sidebar_items': ['breadcrumbs.html', 'page-toc', 'article-header-buttons.html']}
html_title = 'JupyterBook 快速入门'
language = 'zh_CN'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'force'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
tippy_anchor_parent_selector = 'article.bd-article'
tippy_enable_mathjax = True
use_jupyterbook_latex = True
use_multitoc_numbering = False
